// exchanges types
export const FETCH_EXCHANGES = "FETCH_EXCHANGES";
export const FETCH_EXCHANGE_ASSETS = "FETCH_EXCHANGE_ASSETS";

// currentUser types
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const UPDATE_CURRENT_ACCOUNT = "UPDATE_CURRENT_ACCOUNT";
export const FETCH_BALANCES = "FETCH_BALANCES";
export const FETCH_BALANCE_HISTORY = "FETCH_BALANCE_HISTORY";
export const ACCOUNT_CREATED = "ACCOUNT_CREATED";
export const START_CREATE_ACCOUNT = "START_CREATE_ACCOUNT";
export const END_CREATE_ACCOUNT = "END_CREATE_ACCOUNT";
export const ACCOUNT_CREATED_SUCCESS = "ACCOUNT_CREATED_SUCCESS";
export const FETCH_PERMISSIONS = "FETCH_PERMISSIONS";
export const PERMISSIONS_UPDATED = "PERMISSIONS_UPDATED";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const USER_DATA_UPDATED = "USER_DATA_UPDATED";
export const RESET_USER_ACCOUNT_INFO = "RESET_USER_ACCOUNT_INFO";
export const FETCH_REBALANCE_PERIOD = "FETCH_REBALANCE_PERIOD";
export const REBALANCE_PERIOD_UPDATED = "REBALANCE_PERIOD_UPDATED";
export const REBALANCE_INITIATED = "REBALANCE_INITIATED";
export const FETCH_REBALANCE_STRATEGY = "FETCH_REBALANCE_STRATEGY";
export const REBALANCE_STRATEGY_UPDATED = "REBALANCE_STRATEGY_UPDATED";
export const CLEAR_REBALANCE_STRATEGY = "CLEAR_REBALANCE_STRATEGY";

// users types
export const FETCH_USER = "FETCH_USER";
export const FETCH_USERS = "FETCH_USERS";

// general types
export const SHOW_ERRORS = "SHOW_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";
export const SHOW_SPINNER = "SHOW_SPINNER";
export const END_SHOW_SPINNER = "END_SHOW_SPINNER";

// trades types
export const FETCH_TRADES = "FETCH_TRADES";
export const TRADE_SELECT_INPUT = "TRADE_SELECT_INPUT";
export const TRADE_SELECT_OUTPUT = "TRADE_SELECT_OUTPUT";
export const SHOW_TRADE_MODAL = "SHOW_TRADE_MODAL";
export const CLOSE_TRADE_MODAL = "CLOSE_TRADE_MODAL";
export const UPDATE_TRADE_DETAILS = "UPDATE_TRADE_DETAILS";
export const TRADE_SELECT_OUTPUT_VALUE = "TRADE_SELECT_OUTPUT_VALUE";
export const TRADE_SELECT_INPUT_VALUE = "TRADE_SELECT_INPUT_VALUE";
export const UPDATE_MODAL_TYPE = "UPDATE_MODAL_TYPE";
export const UPDATE_LATEST_TRADE = "UPDATE_LATEST_TRADE";
export const SUBMIT_TRADE_START = "SUBMIT_TRADE_START";
export const SUBMIT_TRADE_END = "SUBMIT_TRADE_END";

// rebalance types
export const SHOW_REBALANCE_PERIOD_MODAL = "SHOW_REBALANCE_PERIOD_MODAL";
export const SHOW_REBALANCE_ASSET_SELECT_MODAL =
  "SHOW_REBALANCE_ASSET_SELECT_MODAL";
export const CLOSE_REBALANCE_PERIOD_MODAL = "CLOSE_REBALANCE_PERIOD_MODAL";
export const CLOSE_REBALANCE_ASSET_SELECT_MODAL =
  "CLOSE_REBALANCE_ASSET_SELECT_MODAL";
